name: CD

on:
  push:
    branches:
      - master

jobs:
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 19

      - name: Make Gradlew executable
        run: chmod +x ./gradlew

      - name: Build project
        run: ./gradlew clean bootJar --no-daemon

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ms-ticket:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ms-ticket:latest
